version: 2
jobs:
  deploy-website:
    docker:
      - image: circleci/node:10.16
    working_directory: ~/macbook-setup

    steps:
      - checkout
      - restore_cache:
          keys:
            - root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            # Fallback in case checksum fails
            - root-yarn-{{ .Branch }}-
      - run: yarn --no-progress --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - website/node_modules
          key: root-yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: GIT_USER=bhongy yarn publish-gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy-website:
          filters:
            branches:
              ignore: gh-pages